### PR TITLE
German translation of the Metamath book

### PR DESCRIPTION
**Pull request by avekens**
The German translation of the Metamath book is provided as PDF file in the download folder, and a link to it is added to the Homepage of Metamath (https://us.metamath.org/index.html#book).

For more information see Google group https://groups.google.com/g/metamath/c/W_4qbiqycx8/m/0FRhZ9dRAQAJ

### CODE REVIEW

**Comment by xamidi** [comment]
Nice translation as far as I can see. An error that I noticed:
Page 5 - "schreiben,das" has a space missing after the comma. My suggestion: Use some regular expression searches to avoid very common grammar mistakes.

**Review by jkingdon — APPROVED** [review]

**Review by xamidi — APPROVED** [review]

**Comment by digama0** [comment]
This is really impressive work, I can't imagine how long this took you (and Georg M., who is that if you don't mind me asking?).

Could you release the TeX sources for book? It will make it easier to maintain this going forward.

Typographical issues I noticed on a quick read:

* p. 49: missing a space / indentation in the code comment "Beweisen eines Theorems"
* p. 61: there are some funny quotes at `Replace "‘$6"’ with "‘( + 0 ) ="’`, is this actually what metamath outputs or is this a latex mangling? (EDIT: the same seems to be true of all occurrences of `"` in metamath output, e.g. p. 116)
* p. 65: the chapter heading for 2.5 collides with the page number
* p. 72: https://de.wikipedia.org/wiki/Wahrheitstabelle suggests that truth tables in german conventionally use "W" and "F instead of "T" and "F"
* p. 74: There is a rather long centered line, I haven't checked the original but it looks a bit awkward
* p.  78: there is an unbalanced bracket in the Vereinigungsaxiom
* p. 79: missing a space before set.mm
* p. 80: "where x does not occur in phi" appears untranslated in the math expression
* p. 94: Do the "1-1" and "onto" symbols require clarification in the text?
* p. 110: `(ph -> ")` is missing an open quote
* p. 112: the line breaking in the table headers seem to all be in bad places
* p. 131: Should Whitespace be "Leerraum" or is this a known loan-word?
* p. 135: extra space in `Symbol ,`
* p. 139: should the comment on ax5eq be translated? (This was once the actual comment on the theorem, but it no longer is: https://us.metamath.org/mpeuni/ax5eq.html )
* p. 143: suggest changing the metasyntactic identifier `typecode` to `Typcode`, and `proof` to `Beweis`. (I'm not sure whether it is conventional to capitalize such identifiers, `math-symbol` could similarly be capitalized.)
* p. 149: the math text is not translated
* p. 159: the comment is not translated (maybe not, writing german text in metamath comments is a bit problematic due to all the plain text keywords so maybe it's best to keep it in english)
* p. 164: the `"` issue makes the table very confusing
* p. 164: LaTeXDefinition probably needs a hyphen
* p. 166: I think `command arg arg` would be `befehl arg arg`
* p. 169: `label-list` -> `label-liste`, `compressed-proof` -> `komprimierte-beweis`?
* p. 169: `statement` -> `anweisung`
* p. 186: not sure how to translate `label-match` and `symbol-match`
* p. 186: `show proof` syntax line is untranslated
* p. 187: `number` -> `zahl` (also in other commands)
* p. 189: `proof shortened by` should be capitalized
* p. 191: `\` appears in place of `"`
* p. 191: `symbol sequence` -> `symbolfolge`
* p. 192: `or match all` -> `oder match all`
* p. 195: `symbol-sequence` -> `symbolfolge`
* p. 217: `for` -> `für` or `für alle`
* p. 229: `Äquivalenz , Konjunktion,,` has a space before a comma and then two commas
* p. 239: I think all of the metasyntactic identifiers like `outermost-scope-stmt` should be translated as above

PS: It's a bit sad that the metamath-exe text is all in english, it's a pretty chatty software so it would be nice if it was also translated. If you are up for continuing this work I'd be happy to set up the architecture for metamath-exe to be able to produce german text. (If not, that's fine too, I'm sure you are ready to be done with this!)

**Comment by avekens** [comment]
> Nice translation as far as I can see. An error that I noticed: Page 5 - "schreiben,das" has a space missing after the comma. My suggestion: Use some regular expression searches to avoid very common grammar mistakes.

I will fix it with the next commit, And many thanks for the hint using regular expressions. Although it is not so straight forward in LaTX-sources (many technical cases in which there is no space after "," or "."), I found 5-6 additional cases of a missing space.

**Comment by avekens** [comment]
> This is really impressive work, I can't imagine how long this took you (and Georg M., who is that if you don't mind me asking?).

Georg is my son, without his help/support I coud not have finished this work (at least not until now).

> Could you release the TeX sources for book? It will make it easier to maintain this going forward.

As I have written in the Google group, I plan to provide it in the repository https://github.com/metamath/metamath-book (maybe after this PR is accepted and merged), where also the original book is located and maintained. 

> Typographical issues I noticed on a quick read:

Thanks a lot for them. I will fix these and commit the changed document to this PR.

**Comment by avekens** [comment]
I have fixed most of Mario's issues with my latest commit:

> Typographical issues I noticed on a quick read:
> 
>     * p. 49: missing a space / indentation in the code comment "Beweisen eines Theorems"

done

>     * p. 61: there are some funny quotes at `Replace "‘$6"’ with "‘( + 0 ) ="’`, is this actually what metamath outputs or is this a latex mangling? (EDIT: the same seems to be true of all occurrences of `"` in metamath output, e.g. p. 116)

done: there were sevral issues with ", which had to be replaced by "‘ and "’ for German quotation marks (in the continuous text), but should not in technical texts.

>     * p. 65: the chapter heading for 2.5 collides with the page number

done

>     * p. 72: https://de.wikipedia.org/wiki/Wahrheitstabelle suggests that truth tables in german conventionally use "W" and "F instead of "T" and "F"

done

>     * p. 74: There is a rather long centered line, I haven't checked the original but it looks a bit awkward

done: this is also the case in the original text, by I reformatted the German translation.
 
>     * p.  78: there is an unbalanced bracket in the Vereinigungsaxiom

done

>     * p. 79: missing a space before set.mm

done

>     * p. 80: "where x does not occur in phi" appears untranslated in the math expression

done
 
>     * p. 94: Do the "1-1" and "onto" symbols require clarification in the text?

done: I added some more information
 
>     * p. 110: `(ph -> ")` is missing an open quote

done
 
>     * p. 112: the line breaking in the table headers seem to all be in bad places

done: this is also the case in the original text, by I reformatted the German translation.

>     * p. 131: Should Whitespace be "Leerraum" or is this a known loan-word?

"Leerraum" may be the official translation, but it is not commonly used in German, see also footnote on page 126. Therefore, I would like to keep "Whitespace".

>     * p. 135: extra space in `Symbol ,`

done

>     * p. 139: should the comment on ax5eq be translated? (This was once the actual comment on the theorem, but it no longer is: https://us.metamath.org/mpeuni/ax5eq.html )

I don't think so, this is an extract from (an older version of) set.mm. Since the current version contains only technical, bracketed additions, I would not change it.

>     * p. 143: suggest changing the metasyntactic identifier `typecode` to `Typcode`, and `proof` to `Beweis`. (I'm not sure whether it is conventional to capitalize such identifiers, `math-symbol` could similarly be capitalized.)

I think the metasyntactic identifiers should be in English, because metamath is used in English (Capitalization is a (minor) issue in this context). Therefore, I would propose not to change it now (see also many of the following remarks), but this can be continued to be discussed for future updates.

>     * p. 149: the math text is not translated

done

>     * p. 159: the comment is not translated (maybe not, writing german text in metamath comments is a bit problematic due to all the plain text keywords so maybe it's best to keep it in english)

see above

>     * p. 164: the `"` issue makes the table very confusing

done: see above

>     * p. 164: LaTeXDefinition probably needs a hyphen

done
 
>     * p. 166: I think `command arg arg` would be `befehl arg arg`

see above

>     * p. 169: `label-list` -> `label-liste`, `compressed-proof` -> `komprimierte-beweis`?

see above

>     * p. 169: `statement` -> `anweisung`

see above

>     * p. 186: not sure how to translate `label-match` and `symbol-match`

see above

>     * p. 186: `show proof` syntax line is untranslated

partially done, rest see above

>     * p. 187: `number` -> `zahl` (also in other commands)

see above

>     * p. 189: `proof shortened by` should be capitalized

done

>     * p. 191: `\` appears in place of `"`

done: see above

>     * p. 191: `symbol sequence` -> `symbolfolge`

see above

>     * p. 192: `or match all` -> `oder match all`

done

>     * p. 195: `symbol-sequence` -> `symbolfolge`

see above

>     * p. 217: `for` -> `für` or `für alle`

done ("mit" is the usual word in German in this case)

>     * p. 229: `Äquivalenz , Konjunktion,,` has a space before a comma and then two commas

done

>     * p. 239: I think all of the metasyntactic identifiers like `outermost-scope-stmt` should be translated as above

see above

**Comment by avekens** [comment]
I would propose to finalize this PR if there are no major issues anymore, and can discuss/perform improvements based on the LaTeX source which I will upload to repository https://github.com/metamath/metamath-book (probably today).

**Comment by digama0** [comment]
> I think the metasyntactic identifiers should be in English, because metamath is used in English (Capitalization is a (minor) issue in this context). Therefore, I would propose not to change it now (see also many of the following remarks), but this can be continued to be discussed for future updates.

My thinking is that we should ideally be able to have a full-German experience here, like a properly translated system: the book is in German, the software speaks German, and while set.mm will continue to be in English one can have a German metamath database without issue and then it is possible to not really come in contact with English. At least, this to me seems like the ideal end-state for a proper localization.

But, I'm not the target audience for this book, so I will let you make the editorial decisions. I don't have any additional suggestions, so if you are ready then I'll merge it.

**Review by digama0 — APPROVED** [review]

**Comment by avekens** [comment]
I just provided the LaTeX sources as PR https://github.com/metamath/metamath-book/pull/244. In addition I will create an issue in the metamath-book repository for the discussion about how far English content should be translated.

Therefore, this PR can be merged now (I do not have write access to do it by myself).

**Comment by avekens** [comment]
> PS: It's a bit sad that the metamath-exe text is all in english, it's a pretty chatty software so it would be nice if it was also translated. If you are up for continuing this work I'd be happy to set up the architecture for metamath-exe to be able to produce german text. (If not, that's fine too, I'm sure you are ready to be done with this!)

So you want to internationalize metamath.exe? If this is not too hard and effortful, this would be great. I would volunteer to provide the German translation of the English texts with pleasure. The architecture you are talking of would be based on property files (key/value pairs), one file for each language? This would make it easy to maintain the texts.

**Pull request merged**
