### PR TITLE
remove files duplicated from other repos

### PR DESCRIPTION
**Pull request by digama0**
One of the first things the install script does is to [delete any `.gif` files already present](https://github.com/metamath/metamath-website-scripts/blob/main/install.sh#L327-L331) in the https://github.com/metamath/symbols repo, so these files are useless. This is part of an effort to decrease the number of duplicate files in the website generation, so it is clearer which ones are actually "golden files" and which ones are just overwritten.

### CODE REVIEW

**Comment by benjub** [comment]
Removing duplicate is badly needed, so thanks for that.

Actually, removing gif support everywhere would simplify many things.

**Comment by digama0** [comment]
I found another copy of the symbols in this project, the `symbols/` directory is a copy of the symbols repo except that it lacks some of the GIF files. This is observable on the site, for example https://us.metamath.org/mpegif/_0dot.html is a 404 even though https://github.com/metamath/symbols/blob/main/symbols/_0dot.gif exists, because `install.sh` uses the symbols from this site rather than the other repo.

Don't merge this yet, it will break the site if we do not modify install.sh to match.

**Comment by digama0** [comment]
There are also a bunch of really old `*.mm` files, which are now replicated on https://github.com/metamath/set.mm/ repo, and the metamath sources, which are replicated on https://github.com/metamath/metamath-exe . (This last bit will require some work, because it includes `metamath.exe`, which we will need to cross compile during the linux website build.)

**Review by benjub — APPROVED** [review]
This huge simpification is delightful.

**Comment by digama0** [comment]
If no one objects I will merge all the PRs in this series in about 24 hours, unless there are additional concerns brought up (please speak up if you think something is out of place).

**Pull request merged**
