### PR TITLE
Fix more references to contacting Norm

### PR DESCRIPTION
**Pull request by jkingdon**
These are fairly minimal edits focused just on text which has an email address or specific language around who to contact.

### CODE REVIEW

**Review by digama0 — APPROVED** [review]

**Comment by jkingdon** [comment]
Apparently I don't have the ability to merge pull requests here, but this is ready to merge as far as I can tell.

**Comment by digama0** [comment]
Let's merge it then, I should probably get in the habit of also doing merges here instead of just leaving it to DAW all the time...

**Comment by david-a-wheeler** [comment]
DAW is grateful! :-)

@jkingdom - you seem like a generally trustworthy sort, so I've added you to the people who can merge things in. Remember, with great power comes great responsibility! :-) :-)

**Comment by jkingdon** [comment]
> DAW is grateful! :-)
> 
> @jkingdom - you seem like a generally trustworthy sort, so I've added you to the people who can merge things in. Remember, with great power comes great responsibility! :-) :-)

Heh, thanks. I may use this sparingly, unless/until I better understand what the various files do here.

**Pull request merged**
