### PR TITLE
Fix URL of 100 Theorem

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This is a trivlal fix of 2 URLs, so I'm just going to merge it.

**Comment by benjub** [comment]
There is a file `index.html` in this repo and also one in the repo `set.mm`, which was just modified in a recent PR too: https://github.com/metamath/set.mm/pull/3297. Which one makes it to the web ? Shouldn't there be only one to avoid synchronization problems ?

**Comment by david-a-wheeler** [comment]
> There is a file index.html in this repo and also one in the repo set.mm, which was just modified in a recent PR too: https://github.com/metamath/set.mm/pull/3297. Which one makes it to the web ? Shouldn't there be only one to avoid synchronization problems ?

They both make it to the web, in different directories, so there's no synchronization problem.

**Comment by benjub** [comment]
> > There is a file index.html in this repo and also one in the repo set.mm, which was just modified in a recent PR too: [metamath/set.mm#3297](https://github.com/metamath/set.mm/pull/3297). Which one makes it to the web ? Shouldn't there be only one to avoid synchronization problems ?
> 
> They both make it to the web, in different directories, so there's no synchronization problem.

Which one is the source for https://us.metamath.org/index.html and where does the other one go ?

**Comment by david-a-wheeler** [comment]
> Which one is the source for https://us.metamath.org/index.html 

This repo, `metamath-website-seed`, is the source for that page.

> where does the other one go ?

I don't think the set.mm "index.html" file goes anywhere, I think it's just ignored. We should probably delete it.

**Comment by benjub** [comment]
Ok. So not both make it to the web. Therefore, as written above, there are synchronization problems, and only one should be kept.

Since you maintain the website, and thank you for that, choose the one which is most convenient to you, probably the one in this repo. Then, the changes from https://github.com/metamath/set.mm/pull/3297 should be backported.  Since I think you currently have not much time, I can do a PR here probably next weekend, and then I'll delete the `index.html` in the repo `metamath/set.mm` to avoid further problems.

**Comment by david-a-wheeler** [comment]
That'd be great! Thank you for your time as well.

**Pull request merged**
